spring:
  application:
    name: CodeSupplierService
  config:
    import: optional:configserver:http://localhost:8989/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
css:
  cds:
    src: https://github.com/kuylim/sa-cds/archive/refs/heads/main.zip
    projectName: sa-cds-main #reponame-branchname
  ss:
    src: https://github.com/gedyeyasu/spring-kafka-streams/archive/refs/heads/main.zip
    projectName: spring-kafka-streams-main
  rs:
    src: na #rs service does not need code generation service
    projectName: na

cssTempDir: ${HOME}/csstempdir
zipDir: ${cssTempDir}/zips
codeDir: ${cssTempDir}/codes
zipOutDir: ${cssTempDir}/zipOut
