spring:
  application:
    name: CodeSupplierService
  config:
    import: optional:configserver:http://localhost:8989/

css:
  localCodeDir: ../../../../rawtestcode
  cds:
    src: ${css.localCodeDir}/CDS.java
  ss:
    src: ${css.localCodeDir}/SS.java
  rs:
    src: ${css.localCodeDir}/RS.java

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  file: ${LOG_PATH:-./logs}/app.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  encoder:
    pattern: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    class: net.logstash.logback.encoder.LogstashEncoder
    customFields:
      service: my-service
      environment: dev
      host: ${HOSTNAME}

# Logstash configuration
logstash:
  host: localhost
  port: 5000
