spring:
  application:
    name: CodeSupplierService
  config:
    import: optional:configserver:http://localhost:8989/

css:
  cds:
    src: https://github.com/mrranjan31paudel/sa-project-css/archive/refs/heads/main.zip
  ss:
    src: vvv
  rs:
    src: vvv

cssTempDir: ${HOME}/csstempdir
zipDir: ${cssTempDir}/zips
codeDir: ${cssTempDir}/codes
zipOutDir: ${cssTempDir}/zipOut
