spring:
  profiles:
    active: native
  config:
    import:
  application:
    name: ConfigServer

server:
  port: 8989

  eureka:
    client:
      serviceUrl:
        defaultZone:http://localhost:8761/eureka/


#---
#
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/mrranjan31paudel/SWA-MIU-LABS.git
#          searchPaths:
#            - lab10_part_3/*
#  profiles:
#    active: git
#server:
#  port: 8989
